name: Deploy

on:
  push:
    tags:
      - 'picto@*'

jobs:
  deploy:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build library
        run: |
          yarn
          yarn build

      - name: Build example
        run: |
          yarn
          yarn build
        working-directory: example

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
          BRANCH: gh-pages
          FOLDER: example/public
