name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    if: ${{ startsWith(github.event.head_commit.message, '[Release]') == false }}

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Config
        run: |
          git config --local user.email "tech+githubbot@pretto.fr"
          git config --local user.name "pretto-bot"
      
      - name: Version
        run: npm version minor -m "[Release] picto@%s"
        
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          branch: master
          tags: true

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build library
        run: |
          yarn
          yarn build
      
      - name: Publish
        run: npm publish

      - name: Build example
        run: |
          yarn
          yarn build
        working-directory: example

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: example/public
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
