name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: ${{ startsWith(github.event.head_commit.message, '[CI]') == false }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Config
        run: |
          git config --local user.email "tech+githubbot@pretto.fr"
          git config --local user.name "pretto-bot"

      - name: Version
        run: npm version minor -m "[CI] picto@%s"

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          branch: master
          tags: true

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build library
        run: |
          yarn
          yarn build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
