name: Push

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: ${{ startsWith(github.event.head_commit.message, '[CI]') == false }}

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Config
        run: |
          git config --local user.email "tech+githubbot@pretto.fr"
          git config --local user.name "pretto-bot"

      - name: Version
        run: npm version minor -m "[CI] picto@%s"

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          branch: master
          tags: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build library
        run: |
          yarn
          yarn build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
