name: Release

on:
  push:
    tags:
      - 'picto@*'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build library
        run: |
          yarn
          yarn build

      - name: Build example
        run: |
          yarn
          yarn build
        working-directory: example

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: example/public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
