name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      
      - name: Version
        run: npm version minor -m "[Release] picto@%s"
        
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          tags: true

#      - name: Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          release_name: ${{ github.ref }}
#          tag_name: ${{ github.ref }}
        
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build library
        run: |
          yarn
          yarn build
      
#      - name: Publish
#        run: npm publish

      - name: Build example
        run: |
          yarn
          yarn build
        working-directory: example

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.PAT }}
          BRANCH: gh-pages
          FOLDER: example/public
