name: Release

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Config
        run: |
          git config --local user.email "tech+githubbot@pretto.fr"
          git config --local user.name "pretto-bot"
      
      - name: Version
        run: npm version minor -m "[Release] picto@%s"
        
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          tags: true
