name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    env:
      GIT_CONFIG_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GIT_CONFIG_NAME: github-actions[bot]

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
        
      - name: Config
        run: |
          git config --local user.email "$GIT_CONFIG_EMAIL"
          git config --local user.name "$GIT_CONFIG_NAME"
      
      - name: Version
        run: npm version minor -m "[Release] picto@%s"
        
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

#      - name: Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          release_name: ${{ github.ref }}
#          tag_name: ${{ github.ref }}
        
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build library
        run: |
          yarn
          yarn build
      
#      - name: Publish
#        run: npm publish

      - name: Build example
        run: |
          yarn
          yarn build
        working-directory: example

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: example/public
          GIT_CONFIG_EMAIL: ${{ env.GIT_CONFIG_EMAIL }}
          GIT_CONFIG_NAME: ${{ env.GIT_CONFIG_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
