name: Release

on:
  push:
    tags:
      - 'picto@*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
