name: Tags

on:
  push:
    tags:
      - 'picto@*'

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build library
        run: |
          yarn
          yarn build

      - name: Build example
        run: |
          yarn
          yarn static
        working-directory: example

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
          BRANCH: gh-pages
          FOLDER: example/public

  release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
